on: pull_request

name: Auto merge Dependabot

jobs:
  automerge:
    runs-on: ubuntu-latest
    outputs:
      actor: ${{github.actor}}
      event: ${{toJSON(github.actor.event)}}
    if: |
      github.actor == 'dependabot[bot]' &&
      startsWith(github.event.pull_request.title, 'chore(deps-dev):')
    steps:
      - name: '@dependabot merge'
        uses: actions/github-script@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
